// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrV5lcAKhJylWpnT9BWRAf8AEYr7C0H8Q',
    appId: '1:634213749614:web:ef0a702102b06bf765677f',
    messagingSenderId: '634213749614',
    projectId: 'karachi-biennale-83f05',
    authDomain: 'karachi-biennale-83f05.firebaseapp.com',
    storageBucket: 'karachi-biennale-83f05.firebasestorage.app',
    measurementId: 'G-4S2JN5E07X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcJP5wWW1-oBgjssxlrctvTgTTcQwdlWY',
    appId: '1:634213749614:android:22067fe9374285ff65677f',
    messagingSenderId: '634213749614',
    projectId: 'karachi-biennale-83f05',
    storageBucket: 'karachi-biennale-83f05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuGiEM-59404Ww-rSGk8Hah4vjCs8AQHo',
    appId: '1:634213749614:ios:a6822cb100f5ae1165677f',
    messagingSenderId: '634213749614',
    projectId: 'karachi-biennale-83f05',
    storageBucket: 'karachi-biennale-83f05.firebasestorage.app',
    iosBundleId: 'com.example.karachiBiennale',
  );
}
